// SPDX-FileCopyrightText: Copyright ApiGear UG and Epic Games, Inc.
// SPDX-License-Identifier: MIT
// This file has been generated by the ApiGear Code Generator.
// Do not edit. Changes will be lost when the code is re-generated.
#include "TbIfaceimportSettings.h"
#include "TbIfaceimport/Generated/TbIfaceimportFactory.h"
#include "TbIfaceimport/Generated/TbIfaceimportLogCategories.h"
#include "ApiGearConnectionsStore.h"
#include "Engine/Engine.h"
#include "Misc/CoreDelegates.h"

UTbIfaceimportSettings::UTbIfaceimportSettings(const FObjectInitializer& ObjectInitializer)
	: Super(ObjectInitializer)
{
	FCoreDelegates::OnPostEngineInit.AddUObject(this, &UTbIfaceimportSettings::ValidateSettingsPostEngineInit);
}

void UTbIfaceimportSettings::ValidateSettingsPostEngineInit()
{
	check(GEngine);
	UApiGearConnectionsStore* AGCM = GEngine->GetEngineSubsystem<UApiGearConnectionsStore>();

	if (!AGCM->DoesConnectionExist(OLinkConnectionIdentifier))
	{
		UE_LOG(LogTbIfaceimport, Warning, TEXT("UTbIfaceimportSettings could not find connection %s."), *OLinkConnectionIdentifier);
		OLinkConnectionIdentifier = "";
	}

	// the local backend does not require configuration
	if (TracerServiceIdentifier == TbIfaceimportLocalBackendIdentifier)
	{
		return;
	}

	if (!AGCM->DoesConnectionExist(TracerServiceIdentifier))
	{
		UE_LOG(LogTbIfaceimport, Warning, TEXT("UTbIfaceimportSettings could not find connection %s, falling back to local backend."), *TracerServiceIdentifier);
		TracerServiceIdentifier = TbIfaceimportLocalBackendIdentifier;
	}
}

TScriptInterface<ITbIfaceimportEmptyIfInterface> UTbIfaceimportSettings::GetITbIfaceimportEmptyIfInterfaceForLogging(FSubsystemCollectionBase& Collection)
{
	UTbIfaceimportSettings* TbIfaceimportSettings = GetMutableDefault<UTbIfaceimportSettings>();

	FString BackendIdentifier = TbIfaceimportSettings->TracerServiceIdentifier;

	if (TbIfaceimportSettings->TracerServiceIdentifier == TbIfaceimportLocalBackendIdentifier)
	{
		return FTbIfaceimportModuleFactory::GetTbIfaceimportEmptyIfImplementation(TbIfaceimportLocalBackendIdentifier, Collection);
	}

	if (TbIfaceimportSettings->TracerServiceIdentifier != TbIfaceimportLocalBackendIdentifier)
	{
		return FTbIfaceimportModuleFactory::GetTbIfaceimportEmptyIfImplementation("olink", Collection);
	}

	return nullptr;
}
