// SPDX-FileCopyrightText: Copyright ApiGear UG and Epic Games, Inc.
// SPDX-License-Identifier: MIT
// This file has been generated by the ApiGear Code Generator.
// Do not edit. Changes will be lost when the code is re-generated.

#include "ExternTypesEditor.h"
#include "ISettingsModule.h"
#include "PropertyEditorModule.h"
#include "ExternTypesSettings.h"
#include "ExternTypesConnectionSettings.h"

#define LOCTEXT_NAMESPACE "ExternTypesEditor"

void FExternTypesEditorModule::StartupModule()
{
	// register settings
	ISettingsModule* SettingsModule = FModuleManager::GetModulePtr<ISettingsModule>("Settings");

	if (SettingsModule != nullptr)
	{
		SettingsModule->RegisterSettings("Project", "Plugins", "ApiGear ExternTypes", LOCTEXT("ExternTypesSettingsName", "ApiGear ExternTypes"), LOCTEXT("ExternTypesSettingsDescription", "Project settings for ApiGear ExternTypes plugin"), GetMutableDefault<UExternTypesSettings>());
	}

	// register details customization
	FPropertyEditorModule& PropertyModule = FModuleManager::LoadModuleChecked<FPropertyEditorModule>(TEXT("PropertyEditor"));
	PropertyModule.RegisterCustomClassLayout("ExternTypesSettings", FOnGetDetailCustomizationInstance::CreateStatic(&FExternTypesConnectionSettingsDetails::MakeInstance));
}

void FExternTypesEditorModule::ShutdownModule()
{
	// unregister settings
	ISettingsModule* SettingsModule = FModuleManager::GetModulePtr<ISettingsModule>("Settings");

	if (SettingsModule != nullptr)
	{
		SettingsModule->UnregisterSettings("Project", "Plugins", "ApiGear ExternTypes");
	}
}

IMPLEMENT_MODULE(FExternTypesEditorModule, ExternTypesEditor)

#undef LOCTEXT_NAMESPACE
