// SPDX-FileCopyrightText: Copyright ApiGear UG and Epic Games, Inc.
// SPDX-License-Identifier: MIT
// This file has been generated by the ApiGear Code Generator.
// Do not edit. Changes will be lost when the code is re-generated.
#include "CounterSettings.h"
#include "Counter/Generated/CounterFactory.h"
#include "Counter/Generated/CounterLogCategories.h"
#include "ApiGearConnectionsStore.h"
#include "Engine/Engine.h"
#include "Misc/CoreDelegates.h"

UCounterSettings::UCounterSettings(const FObjectInitializer& ObjectInitializer)
	: Super(ObjectInitializer)
{
	FCoreDelegates::OnPostEngineInit.AddUObject(this, &UCounterSettings::ValidateSettingsPostEngineInit);
}

void UCounterSettings::ValidateSettingsPostEngineInit()
{
	check(GEngine);
	UApiGearConnectionsStore* AGCM = GEngine->GetEngineSubsystem<UApiGearConnectionsStore>();

	if (!AGCM->DoesConnectionExist(OLinkConnectionIdentifier))
	{
		UE_LOG(LogCounter, Warning, TEXT("UCounterSettings could not find connection %s."), *OLinkConnectionIdentifier);
		OLinkConnectionIdentifier = "";
	}

	// the local backend does not require configuration
	if (TracerServiceIdentifier == CounterLocalBackendIdentifier)
	{
		return;
	}

	if (!AGCM->DoesConnectionExist(TracerServiceIdentifier))
	{
		UE_LOG(LogCounter, Warning, TEXT("UCounterSettings could not find connection %s, falling back to local backend."), *TracerServiceIdentifier);
		TracerServiceIdentifier = CounterLocalBackendIdentifier;
	}
}

TScriptInterface<ICounterCounterInterface> UCounterSettings::GetICounterCounterInterfaceForLogging(FSubsystemCollectionBase& Collection)
{
	UCounterSettings* CounterSettings = GetMutableDefault<UCounterSettings>();

	FString BackendIdentifier = CounterSettings->TracerServiceIdentifier;

	if (CounterSettings->TracerServiceIdentifier == CounterLocalBackendIdentifier)
	{
		return FCounterModuleFactory::GetCounterCounterImplementation(CounterLocalBackendIdentifier, Collection);
	}

	if (CounterSettings->TracerServiceIdentifier != CounterLocalBackendIdentifier)
	{
		return FCounterModuleFactory::GetCounterCounterImplementation("olink", Collection);
	}

	return nullptr;
}
