// SPDX-FileCopyrightText: Copyright ApiGear UG and Epic Games, Inc.
// SPDX-License-Identifier: MIT
// This file has been generated by the ApiGear Code Generator.
// Do not edit. Changes will be lost when the code is re-generated.
#include "TbStructArray/Tests/TbStructArrayTestsCommon.h"
#include "TbStructArray/Generated/api/TbStructArray_data.h"
#include "Misc/AutomationTest.h"

#if WITH_DEV_AUTOMATION_TESTS
FTbStructArrayPoint createTestFTbStructArrayPoint()
{
	FTbStructArrayPoint TestValue;

	TestValue.x = 1.0f;
	TestValue.y = 1.0f;

	return TestValue;
}

TArray<FTbStructArrayPoint> createTestFTbStructArrayPointArray()
{
	TArray<FTbStructArrayPoint> TestValueArray;

	TestValueArray.Add(createTestFTbStructArrayPoint());

	return TestValueArray;
}

FTbStructArrayStructWithArrayOfStructs createTestFTbStructArrayStructWithArrayOfStructs()
{
	FTbStructArrayStructWithArrayOfStructs TestValue;

	TestValue.points = createTestFTbStructArrayPointArray();

	return TestValue;
}

TArray<FTbStructArrayStructWithArrayOfStructs> createTestFTbStructArrayStructWithArrayOfStructsArray()
{
	TArray<FTbStructArrayStructWithArrayOfStructs> TestValueArray;

	TestValueArray.Add(createTestFTbStructArrayStructWithArrayOfStructs());

	return TestValueArray;
}

FTbStructArrayStructWithArrayOfEnums createTestFTbStructArrayStructWithArrayOfEnums()
{
	FTbStructArrayStructWithArrayOfEnums TestValue;

	TestValue.tags.Add(ETbStructArrayTestEnum::TSATE_Value2);

	return TestValue;
}

TArray<FTbStructArrayStructWithArrayOfEnums> createTestFTbStructArrayStructWithArrayOfEnumsArray()
{
	TArray<FTbStructArrayStructWithArrayOfEnums> TestValueArray;

	TestValueArray.Add(createTestFTbStructArrayStructWithArrayOfEnums());

	return TestValueArray;
}

FTbStructArrayStructWithArrayOfInts createTestFTbStructArrayStructWithArrayOfInts()
{
	FTbStructArrayStructWithArrayOfInts TestValue;

	TestValue.values.Add(1);

	return TestValue;
}

TArray<FTbStructArrayStructWithArrayOfInts> createTestFTbStructArrayStructWithArrayOfIntsArray()
{
	TArray<FTbStructArrayStructWithArrayOfInts> TestValueArray;

	TestValueArray.Add(createTestFTbStructArrayStructWithArrayOfInts());

	return TestValueArray;
}

FTbStructArrayMixedStruct createTestFTbStructArrayMixedStruct()
{
	FTbStructArrayMixedStruct TestValue;

	TestValue.id = 1;
	TestValue.name = FString("xyz");
	TestValue.origin = createTestFTbStructArrayPoint();
	TestValue.points = createTestFTbStructArrayPointArray();
	TestValue.flags.Add(ETbStructArrayTestEnum::TSATE_Value2);
	TestValue.scores.Add(1);

	return TestValue;
}

TArray<FTbStructArrayMixedStruct> createTestFTbStructArrayMixedStructArray()
{
	TArray<FTbStructArrayMixedStruct> TestValueArray;

	TestValueArray.Add(createTestFTbStructArrayMixedStruct());

	return TestValueArray;
}

TArray<ETbStructArrayTestEnum> createTestFTbStructArrayTestEnumArray()
{
	TArray<ETbStructArrayTestEnum> TestValueArray;

	ETbStructArrayTestEnum val = ETbStructArrayTestEnum::TSATE_Value1;
	TestValueArray.Add(val);
	return TestValueArray;
}

#endif // WITH_DEV_AUTOMATION_TESTS
