// SPDX-FileCopyrightText: Copyright ApiGear UG and Epic Games, Inc.
// SPDX-License-Identifier: MIT
// This file has been generated by the ApiGear Code Generator.
// Do not edit. Changes will be lost when the code is re-generated.

#include "TbSame2Editor.h"
#include "ISettingsModule.h"
#include "PropertyEditorModule.h"
#include "TbSame2Settings.h"
#include "TbSame2ConnectionSettings.h"

#define LOCTEXT_NAMESPACE "TbSame2Editor"

void FTbSame2EditorModule::StartupModule()
{
	// register settings
	ISettingsModule* SettingsModule = FModuleManager::GetModulePtr<ISettingsModule>("Settings");

	if (SettingsModule != nullptr)
	{
		SettingsModule->RegisterSettings("Project", "Plugins", "ApiGear TbSame2", LOCTEXT("TbSame2SettingsName", "ApiGear TbSame2"), LOCTEXT("TbSame2SettingsDescription", "Project settings for ApiGear TbSame2 plugin"), GetMutableDefault<UTbSame2Settings>());
	}

	// register details customization
	FPropertyEditorModule& PropertyModule = FModuleManager::LoadModuleChecked<FPropertyEditorModule>(TEXT("PropertyEditor"));
	PropertyModule.RegisterCustomClassLayout("TbSame2Settings", FOnGetDetailCustomizationInstance::CreateStatic(&FTbSame2ConnectionSettingsDetails::MakeInstance));
}

void FTbSame2EditorModule::ShutdownModule()
{
	// unregister settings
	ISettingsModule* SettingsModule = FModuleManager::GetModulePtr<ISettingsModule>("Settings");

	if (SettingsModule != nullptr)
	{
		SettingsModule->UnregisterSettings("Project", "Plugins", "ApiGear TbSame2");
	}
}

IMPLEMENT_MODULE(FTbSame2EditorModule, TbSame2Editor)

#undef LOCTEXT_NAMESPACE
