// SPDX-FileCopyrightText: Copyright ApiGear UG and Epic Games, Inc.
// SPDX-License-Identifier: MIT
// This file has been generated by the ApiGear Code Generator.
// Do not edit. Changes will be lost when the code is re-generated.

#include "TbIfaceimportEditor.h"
#include "ISettingsModule.h"
#include "PropertyEditorModule.h"
#include "TbIfaceimportSettings.h"
#include "TbIfaceimportConnectionSettings.h"

#define LOCTEXT_NAMESPACE "TbIfaceimportEditor"

void FTbIfaceimportEditorModule::StartupModule()
{
	// register settings
	ISettingsModule* SettingsModule = FModuleManager::GetModulePtr<ISettingsModule>("Settings");

	if (SettingsModule != nullptr)
	{
		SettingsModule->RegisterSettings("Project", "Plugins", "ApiGear TbIfaceimport", LOCTEXT("TbIfaceimportSettingsName", "ApiGear TbIfaceimport"), LOCTEXT("TbIfaceimportSettingsDescription", "Project settings for ApiGear TbIfaceimport plugin"), GetMutableDefault<UTbIfaceimportSettings>());
	}

	// register details customization
	FPropertyEditorModule& PropertyModule = FModuleManager::LoadModuleChecked<FPropertyEditorModule>(TEXT("PropertyEditor"));
	PropertyModule.RegisterCustomClassLayout("TbIfaceimportSettings", FOnGetDetailCustomizationInstance::CreateStatic(&FTbIfaceimportConnectionSettingsDetails::MakeInstance));
}

void FTbIfaceimportEditorModule::ShutdownModule()
{
	// unregister settings
	ISettingsModule* SettingsModule = FModuleManager::GetModulePtr<ISettingsModule>("Settings");

	if (SettingsModule != nullptr)
	{
		SettingsModule->UnregisterSettings("Project", "Plugins", "ApiGear TbIfaceimport");
	}
}

IMPLEMENT_MODULE(FTbIfaceimportEditorModule, TbIfaceimportEditor)

#undef LOCTEXT_NAMESPACE
