// SPDX-FileCopyrightText: Copyright ApiGear UG and Epic Games, Inc.
// SPDX-License-Identifier: MIT
// This file has been generated by the ApiGear Code Generator.
// Do not edit. Changes will be lost when the code is re-generated.

#include "CustomTypesEditor.h"
#include "ISettingsModule.h"
#include "PropertyEditorModule.h"
#include "CustomTypesSettings.h"
#include "CustomTypesConnectionSettings.h"

#define LOCTEXT_NAMESPACE "CustomTypesEditor"

void FCustomTypesEditorModule::StartupModule()
{
	// register settings
	ISettingsModule* SettingsModule = FModuleManager::GetModulePtr<ISettingsModule>("Settings");

	if (SettingsModule != nullptr)
	{
		SettingsModule->RegisterSettings("Project", "Plugins", "ApiGear CustomTypes", LOCTEXT("CustomTypesSettingsName", "ApiGear CustomTypes"), LOCTEXT("CustomTypesSettingsDescription", "Project settings for ApiGear CustomTypes plugin"), GetMutableDefault<UCustomTypesSettings>());
	}

	// register details customization
	FPropertyEditorModule& PropertyModule = FModuleManager::LoadModuleChecked<FPropertyEditorModule>(TEXT("PropertyEditor"));
	PropertyModule.RegisterCustomClassLayout("CustomTypesSettings", FOnGetDetailCustomizationInstance::CreateStatic(&FCustomTypesConnectionSettingsDetails::MakeInstance));
}

void FCustomTypesEditorModule::ShutdownModule()
{
	// unregister settings
	ISettingsModule* SettingsModule = FModuleManager::GetModulePtr<ISettingsModule>("Settings");

	if (SettingsModule != nullptr)
	{
		SettingsModule->UnregisterSettings("Project", "Plugins", "ApiGear CustomTypes");
	}
}

IMPLEMENT_MODULE(FCustomTypesEditorModule, CustomTypesEditor)

#undef LOCTEXT_NAMESPACE
