// SPDX-FileCopyrightText: Copyright ApiGear UG and Epic Games, Inc.
// SPDX-License-Identifier: MIT
// This file has been generated by the ApiGear Code Generator.
// Do not edit. Changes will be lost when the code is re-generated.
#pragma once

#include "CoreMinimal.h"
#include "UObject/ObjectMacros.h"
#include "UObject/Object.h"
#include "Engine/EngineTypes.h"
#include "Testbed2Settings.generated.h"

const FString Testbed2LocalBackendIdentifier = "Local";

class FSubsystemCollectionBase;
class ITestbed2ManyParamInterfaceInterface;
class ITestbed2NestedStruct1InterfaceInterface;
class ITestbed2NestedStruct2InterfaceInterface;
class ITestbed2NestedStruct3InterfaceInterface;

/**
 * Implements the settings for the Testbed2 plugin.
 */
UCLASS(Config = Engine, DefaultConfig)
class TESTBED2CORE_API UTestbed2Settings : public UObject
{
	GENERATED_BODY()

	UTestbed2Settings(const FObjectInitializer& ObjectInitializer);

public:
	/** Callback used to validate the settings once the engine is available */
	void ValidateSettingsPostEngineInit();

	/** Choose the backend service for the logging decorator to use */
	UPROPERTY(EditAnywhere, config, Category = TracerServiceSetup)
	FString TracerServiceIdentifier;

	/** Choose the olink connection to use */
	UPROPERTY(EditAnywhere, config, Category = OLinkConnectionSetup)
	FString OLinkConnectionIdentifier;
	static TScriptInterface<ITestbed2ManyParamInterfaceInterface> GetITestbed2ManyParamInterfaceInterfaceForLogging(FSubsystemCollectionBase& Collection);
	static TScriptInterface<ITestbed2NestedStruct1InterfaceInterface> GetITestbed2NestedStruct1InterfaceInterfaceForLogging(FSubsystemCollectionBase& Collection);
	static TScriptInterface<ITestbed2NestedStruct2InterfaceInterface> GetITestbed2NestedStruct2InterfaceInterfaceForLogging(FSubsystemCollectionBase& Collection);
	static TScriptInterface<ITestbed2NestedStruct3InterfaceInterface> GetITestbed2NestedStruct3InterfaceInterfaceForLogging(FSubsystemCollectionBase& Collection);

	/** Choose the heartbeat interval in milliseconds for the msgbus connection on the service side.
	 * On the service side this adjusts the heartbeat between client and service. The clients will receive the value from service.
	 * On the client side this adjusts how often discovery messages are sent until a service is connected.
	 */
	UPROPERTY(EditAnywhere, config, Category = MsgBusConnectionSetup, meta = (DisplayName = "Heartbeat interval (in milliseconds)"))
	uint32 MsgBusHeartbeatIntervalMS = 200;
};
