// SPDX-FileCopyrightText: Copyright ApiGear UG and Epic Games, Inc.
// SPDX-License-Identifier: MIT
// This file has been generated by the ApiGear Code Generator.
// Do not edit. Changes will be lost when the code is re-generated.
using UnrealBuildTool;
using System.IO;

public class TbRefIfacesJni : ModuleRules
{
	public TbRefIfacesJni(ReadOnlyTargetRules Target) : base(Target)
	{
		PCHUsage = ModuleRules.PCHUsageMode.UseExplicitOrSharedPCHs;
		#if UE_5_2_OR_LATER 
			IWYUSupport = IWYUSupport.Full;
		#else
			bEnforceIWYU = true;
		#endif

		// Disable nlohmann::json exception handling
		PublicDefinitions.Add("JSON_NOEXCEPTION=1");

		PublicIncludePaths.AddRange(
			new string[] {
				// ... add public include paths required here ...
			}
			);
				
		
		PrivateIncludePaths.AddRange(
			new string[] {
				// ... add other private include paths required here ...
			}
			);
			
		
		PublicDependencyModuleNames.AddRange(
			new string[]
			{
				"TbRefIfacesAPI",
				"TbRefIfacesCore",
				"Projects",
				"Engine",
				"JsonUtilities",
				"TbIfaceimportCore"
			}
			);
			
		
		PrivateDependencyModuleNames.AddRange(
			new string[]
			{
				"Core",
				"CoreUObject",
				"Engine",
				"TbRefIfacesCore",
				"TbRefIfacesImplementation",
				"TbIfaceimportAPI",
			}
			);

		if (Target.Platform == UnrealTargetPlatform.Android)
        {
            PrivateDefinitions.Add("WITH_JNI=1");
            string PluginPath = Utils.MakePathRelativeTo(ModuleDirectory, Target.RelativeEnginePath);
            AdditionalPropertiesForReceipt.Add("AndroidPlugin", Path.Combine(PluginPath, "TbRefIfaces_JNI_UPL.xml"));

            PublicDependencyModuleNames.AddRange(
                new string[]
                {
                    "TbIfaceimportJni"
                }
                );

            PrivateDependencyModuleNames.AddRange(new string[] { "Launch" });
        }
		
		
		DynamicallyLoadedModuleNames.AddRange(
			new string[]
			{
				// ... add any modules that your module loads dynamically here ...
			}
			);
	}
}
