// SPDX-FileCopyrightText: Copyright ApiGear UG and Epic Games, Inc.
// SPDX-License-Identifier: MIT
// This file has been generated by the ApiGear Code Generator.
// Do not edit. Changes will be lost when the code is re-generated.

#include "Testbed1Editor.h"
#include "ISettingsModule.h"
#include "PropertyEditorModule.h"
#include "Testbed1Settings.h"
#include "Testbed1ConnectionSettings.h"

#define LOCTEXT_NAMESPACE "Testbed1Editor"

void FTestbed1EditorModule::StartupModule()
{
	// register settings
	ISettingsModule* SettingsModule = FModuleManager::GetModulePtr<ISettingsModule>("Settings");

	if (SettingsModule != nullptr)
	{
		SettingsModule->RegisterSettings("Project", "Plugins", "ApiGear Testbed1", LOCTEXT("Testbed1SettingsName", "ApiGear Testbed1"), LOCTEXT("Testbed1SettingsDescription", "Project settings for ApiGear Testbed1 plugin"), GetMutableDefault<UTestbed1Settings>());
	}

	// register details customization
	FPropertyEditorModule& PropertyModule = FModuleManager::LoadModuleChecked<FPropertyEditorModule>(TEXT("PropertyEditor"));
	PropertyModule.RegisterCustomClassLayout("Testbed1Settings", FOnGetDetailCustomizationInstance::CreateStatic(&FTestbed1ConnectionSettingsDetails::MakeInstance));
}

void FTestbed1EditorModule::ShutdownModule()
{
	// unregister settings
	ISettingsModule* SettingsModule = FModuleManager::GetModulePtr<ISettingsModule>("Settings");

	if (SettingsModule != nullptr)
	{
		SettingsModule->UnregisterSettings("Project", "Plugins", "ApiGear Testbed1");
	}
}

IMPLEMENT_MODULE(FTestbed1EditorModule, Testbed1Editor)

#undef LOCTEXT_NAMESPACE
