// SPDX-FileCopyrightText: Copyright ApiGear UG and Epic Games, Inc.
// SPDX-License-Identifier: MIT
// This file has been generated by the ApiGear Code Generator.
// Do not edit. Changes will be lost when the code is re-generated.
#include "TbStructArraySettings.h"
#include "TbStructArray/Generated/TbStructArrayFactory.h"
#include "TbStructArray/Generated/TbStructArrayLogCategories.h"
#include "ApiGearConnectionsStore.h"
#include "Engine/Engine.h"
#include "Misc/CoreDelegates.h"

UTbStructArraySettings::UTbStructArraySettings(const FObjectInitializer& ObjectInitializer)
	: Super(ObjectInitializer)
{
#if ENGINE_MAJOR_VERSION >= 5 && ENGINE_MINOR_VERSION >= 8
	FCoreDelegates::GetOnPostEngineInit().AddUObject(this, &UTbStructArraySettings::ValidateSettingsPostEngineInit);
#else
	FCoreDelegates::OnPostEngineInit.AddUObject(this, &UTbStructArraySettings::ValidateSettingsPostEngineInit);
#endif
}

void UTbStructArraySettings::ValidateSettingsPostEngineInit()
{
	check(GEngine);
	UApiGearConnectionsStore* AGCM = GEngine->GetEngineSubsystem<UApiGearConnectionsStore>();

	if (!AGCM->DoesConnectionExist(OLinkConnectionIdentifier))
	{
		UE_LOG(LogTbStructArray, Warning, TEXT("UTbStructArraySettings could not find connection %s."), *OLinkConnectionIdentifier);
		OLinkConnectionIdentifier = "";
	}

	// the local backend does not require configuration
	if (TracerServiceIdentifier == TbStructArrayLocalBackendIdentifier)
	{
		return;
	}

	if (!AGCM->DoesConnectionExist(TracerServiceIdentifier))
	{
		UE_LOG(LogTbStructArray, Warning, TEXT("UTbStructArraySettings could not find connection %s, falling back to local backend."), *TracerServiceIdentifier);
		TracerServiceIdentifier = TbStructArrayLocalBackendIdentifier;
	}
}

TScriptInterface<ITbStructArrayStructArrayFieldInterfaceInterface> UTbStructArraySettings::GetITbStructArrayStructArrayFieldInterfaceInterfaceForLogging(FSubsystemCollectionBase& Collection)
{
	UTbStructArraySettings* TbStructArraySettings = GetMutableDefault<UTbStructArraySettings>();

	FString BackendIdentifier = TbStructArraySettings->TracerServiceIdentifier;

	if (TbStructArraySettings->TracerServiceIdentifier == TbStructArrayLocalBackendIdentifier)
	{
		return FTbStructArrayModuleFactory::GetTbStructArrayStructArrayFieldInterfaceImplementation(TbStructArrayLocalBackendIdentifier, Collection);
	}

	if (TbStructArraySettings->TracerServiceIdentifier != TbStructArrayLocalBackendIdentifier)
	{
		return FTbStructArrayModuleFactory::GetTbStructArrayStructArrayFieldInterfaceImplementation("olink", Collection);
	}

	return nullptr;
}
