// SPDX-FileCopyrightText: Copyright ApiGear UG and Epic Games, Inc.
// SPDX-License-Identifier: MIT
// This file has been generated by the ApiGear Code Generator.
// Do not edit. Changes will be lost when the code is re-generated.
#include "CustomTypes/Tests/CustomTypesTestsCommon.h"
#include "CustomTypes/Generated/api/CustomTypes_data.h"
#include "Misc/AutomationTest.h"

#if WITH_DEV_AUTOMATION_TESTS
FCustomTypesVector3D createTestFCustomTypesVector3D()
{
	FCustomTypesVector3D TestValue;

	TestValue.x = 1.0f;
	TestValue.y = 1.0f;
	TestValue.z = 1.0f;

	return TestValue;
}

TArray<FCustomTypesVector3D> createTestFCustomTypesVector3DArray()
{
	TArray<FCustomTypesVector3D> TestValueArray;

	TestValueArray.Add(createTestFCustomTypesVector3D());

	return TestValueArray;
}


#endif // WITH_DEV_AUTOMATION_TESTS
