// SPDX-FileCopyrightText: Copyright ApiGear UG and Epic Games, Inc.
// SPDX-License-Identifier: MIT
// This file has been generated by the ApiGear Code Generator.
// Do not edit. Changes will be lost when the code is re-generated.
#include "TbNames/Tests/TbNamesTestsCommon.h"
#include "TbNames/Generated/api/TbNames_data.h"
#include "Misc/AutomationTest.h"

#if WITH_DEV_AUTOMATION_TESTS
TArray<ETbNamesEnum_With_Under_scores> createTestFTbNamesEnum_With_Under_scoresArray()
{
	TArray<ETbNamesEnum_With_Under_scores> TestValueArray;

	ETbNamesEnum_With_Under_scores val = ETbNamesEnum_With_Under_scores::TNEWUS_FirstValue;
	TestValueArray.Add(val);
	return TestValueArray;
}



#endif // WITH_DEV_AUTOMATION_TESTS
