// SPDX-FileCopyrightText: Copyright ApiGear UG and Epic Games, Inc.
// SPDX-License-Identifier: MIT
// This file has been generated by the ApiGear Code Generator.
// Do not edit. Changes will be lost when the code is re-generated.

#include "TbStructArrayEditor.h"
#include "ISettingsModule.h"
#include "PropertyEditorModule.h"
#include "TbStructArraySettings.h"
#include "TbStructArrayConnectionSettings.h"

#define LOCTEXT_NAMESPACE "TbStructArrayEditor"

void FTbStructArrayEditorModule::StartupModule()
{
	// register settings
	ISettingsModule* SettingsModule = FModuleManager::GetModulePtr<ISettingsModule>("Settings");

	if (SettingsModule != nullptr)
	{
		SettingsModule->RegisterSettings("Project", "Plugins", "ApiGear TbStructArray", LOCTEXT("TbStructArraySettingsName", "ApiGear TbStructArray"), LOCTEXT("TbStructArraySettingsDescription", "Project settings for ApiGear TbStructArray plugin"), GetMutableDefault<UTbStructArraySettings>());
	}

	// register details customization
	FPropertyEditorModule& PropertyModule = FModuleManager::LoadModuleChecked<FPropertyEditorModule>(TEXT("PropertyEditor"));
	PropertyModule.RegisterCustomClassLayout("TbStructArraySettings", FOnGetDetailCustomizationInstance::CreateStatic(&FTbStructArrayConnectionSettingsDetails::MakeInstance));
}

void FTbStructArrayEditorModule::ShutdownModule()
{
	// unregister settings
	ISettingsModule* SettingsModule = FModuleManager::GetModulePtr<ISettingsModule>("Settings");

	if (SettingsModule != nullptr)
	{
		SettingsModule->UnregisterSettings("Project", "Plugins", "ApiGear TbStructArray");
	}
}

IMPLEMENT_MODULE(FTbStructArrayEditorModule, TbStructArrayEditor)

#undef LOCTEXT_NAMESPACE
