// SPDX-FileCopyrightText: Copyright ApiGear UG and Epic Games, Inc.
// SPDX-License-Identifier: MIT
// This file has been generated by the ApiGear Code Generator.
// Do not edit. Changes will be lost when the code is re-generated.

#include "TbEnumEditor.h"
#include "ISettingsModule.h"
#include "PropertyEditorModule.h"
#include "TbEnumSettings.h"
#include "TbEnumConnectionSettings.h"

#define LOCTEXT_NAMESPACE "TbEnumEditor"

void FTbEnumEditorModule::StartupModule()
{
	// register settings
	ISettingsModule* SettingsModule = FModuleManager::GetModulePtr<ISettingsModule>("Settings");

	if (SettingsModule != nullptr)
	{
		SettingsModule->RegisterSettings("Project", "Plugins", "ApiGear TbEnum", LOCTEXT("TbEnumSettingsName", "ApiGear TbEnum"), LOCTEXT("TbEnumSettingsDescription", "Project settings for ApiGear TbEnum plugin"), GetMutableDefault<UTbEnumSettings>());
	}

	// register details customization
	FPropertyEditorModule& PropertyModule = FModuleManager::LoadModuleChecked<FPropertyEditorModule>(TEXT("PropertyEditor"));
	PropertyModule.RegisterCustomClassLayout("TbEnumSettings", FOnGetDetailCustomizationInstance::CreateStatic(&FTbEnumConnectionSettingsDetails::MakeInstance));
}

void FTbEnumEditorModule::ShutdownModule()
{
	// unregister settings
	ISettingsModule* SettingsModule = FModuleManager::GetModulePtr<ISettingsModule>("Settings");

	if (SettingsModule != nullptr)
	{
		SettingsModule->UnregisterSettings("Project", "Plugins", "ApiGear TbEnum");
	}
}

IMPLEMENT_MODULE(FTbEnumEditorModule, TbEnumEditor)

#undef LOCTEXT_NAMESPACE
