// SPDX-FileCopyrightText: Copyright ApiGear UG and Epic Games, Inc.
// SPDX-License-Identifier: MIT
// This file has been generated by the ApiGear Code Generator.
// Do not edit. Changes will be lost when the code is re-generated.

#include "TbNamesEditor.h"
#include "ISettingsModule.h"
#include "PropertyEditorModule.h"
#include "TbNamesSettings.h"
#include "TbNamesConnectionSettings.h"

#define LOCTEXT_NAMESPACE "TbNamesEditor"

void FTbNamesEditorModule::StartupModule()
{
	// register settings
	ISettingsModule* SettingsModule = FModuleManager::GetModulePtr<ISettingsModule>("Settings");

	if (SettingsModule != nullptr)
	{
		SettingsModule->RegisterSettings("Project", "Plugins", "ApiGear TbNames", LOCTEXT("TbNamesSettingsName", "ApiGear TbNames"), LOCTEXT("TbNamesSettingsDescription", "Project settings for ApiGear TbNames plugin"), GetMutableDefault<UTbNamesSettings>());
	}

	// register details customization
	FPropertyEditorModule& PropertyModule = FModuleManager::LoadModuleChecked<FPropertyEditorModule>(TEXT("PropertyEditor"));
	PropertyModule.RegisterCustomClassLayout("TbNamesSettings", FOnGetDetailCustomizationInstance::CreateStatic(&FTbNamesConnectionSettingsDetails::MakeInstance));
}

void FTbNamesEditorModule::ShutdownModule()
{
	// unregister settings
	ISettingsModule* SettingsModule = FModuleManager::GetModulePtr<ISettingsModule>("Settings");

	if (SettingsModule != nullptr)
	{
		SettingsModule->UnregisterSettings("Project", "Plugins", "ApiGear TbNames");
	}
}

IMPLEMENT_MODULE(FTbNamesEditorModule, TbNamesEditor)

#undef LOCTEXT_NAMESPACE
