// SPDX-FileCopyrightText: Copyright ApiGear UG and Epic Games, Inc.
// SPDX-License-Identifier: MIT
// This file has been generated by the ApiGear Code Generator.
// Do not edit. Changes will be lost when the code is re-generated.
#pragma once

#include "TbStructArray/Generated/api/TbStructArray_data.h"
#include "Runtime/Launch/Resources/Version.h"
#include "Misc/AutomationTest.h"

#if WITH_DEV_AUTOMATION_TESTS

#if (ENGINE_MAJOR_VERSION >= 5)
#if (ENGINE_MINOR_VERSION >= 5)
inline constexpr EAutomationTestFlags TbStructArrayTestFilterMask = EAutomationTestFlags_ApplicationContextMask | EAutomationTestFlags::ProductFilter;
#else
inline constexpr int TbStructArrayTestFilterMask = EAutomationTestFlags::ApplicationContextMask | EAutomationTestFlags::ProductFilter;
#endif
#else
constexpr int TbStructArrayTestFilterMask = EAutomationTestFlags::ApplicationContextMask | EAutomationTestFlags::ProductFilter;
#endif

FTbStructArrayPoint TBSTRUCTARRAYCORE_API createTestFTbStructArrayPoint();

TArray<FTbStructArrayPoint> TBSTRUCTARRAYCORE_API createTestFTbStructArrayPointArray();

FTbStructArrayStructWithArrayOfStructs TBSTRUCTARRAYCORE_API createTestFTbStructArrayStructWithArrayOfStructs();

TArray<FTbStructArrayStructWithArrayOfStructs> TBSTRUCTARRAYCORE_API createTestFTbStructArrayStructWithArrayOfStructsArray();

FTbStructArrayStructWithArrayOfEnums TBSTRUCTARRAYCORE_API createTestFTbStructArrayStructWithArrayOfEnums();

TArray<FTbStructArrayStructWithArrayOfEnums> TBSTRUCTARRAYCORE_API createTestFTbStructArrayStructWithArrayOfEnumsArray();

FTbStructArrayStructWithArrayOfInts TBSTRUCTARRAYCORE_API createTestFTbStructArrayStructWithArrayOfInts();

TArray<FTbStructArrayStructWithArrayOfInts> TBSTRUCTARRAYCORE_API createTestFTbStructArrayStructWithArrayOfIntsArray();

FTbStructArrayMixedStruct TBSTRUCTARRAYCORE_API createTestFTbStructArrayMixedStruct();

TArray<FTbStructArrayMixedStruct> TBSTRUCTARRAYCORE_API createTestFTbStructArrayMixedStructArray();

TArray<ETbStructArrayTestEnum> TBSTRUCTARRAYCORE_API createTestFTbStructArrayTestEnumArray();

#endif // WITH_DEV_AUTOMATION_TESTS
