// SPDX-FileCopyrightText: Copyright ApiGear UG and Epic Games, Inc.
// SPDX-License-Identifier: MIT
// This file has been generated by the ApiGear Code Generator.
// Do not edit. Changes will be lost when the code is re-generated.

#include "TbSimpleEditor.h"
#include "ISettingsModule.h"
#include "PropertyEditorModule.h"
#include "TbSimpleSettings.h"
#include "TbSimpleConnectionSettings.h"

#define LOCTEXT_NAMESPACE "TbSimpleEditor"

void FTbSimpleEditorModule::StartupModule()
{
	// register settings
	ISettingsModule* SettingsModule = FModuleManager::GetModulePtr<ISettingsModule>("Settings");

	if (SettingsModule != nullptr)
	{
		SettingsModule->RegisterSettings("Project", "Plugins", "ApiGear TbSimple", LOCTEXT("TbSimpleSettingsName", "ApiGear TbSimple"), LOCTEXT("TbSimpleSettingsDescription", "Project settings for ApiGear TbSimple plugin"), GetMutableDefault<UTbSimpleSettings>());
	}

	// register details customization
	FPropertyEditorModule& PropertyModule = FModuleManager::LoadModuleChecked<FPropertyEditorModule>(TEXT("PropertyEditor"));
	PropertyModule.RegisterCustomClassLayout("TbSimpleSettings", FOnGetDetailCustomizationInstance::CreateStatic(&FTbSimpleConnectionSettingsDetails::MakeInstance));
}

void FTbSimpleEditorModule::ShutdownModule()
{
	// unregister settings
	ISettingsModule* SettingsModule = FModuleManager::GetModulePtr<ISettingsModule>("Settings");

	if (SettingsModule != nullptr)
	{
		SettingsModule->UnregisterSettings("Project", "Plugins", "ApiGear TbSimple");
	}
}

IMPLEMENT_MODULE(FTbSimpleEditorModule, TbSimpleEditor)

#undef LOCTEXT_NAMESPACE
