// SPDX-FileCopyrightText: Copyright ApiGear UG and Epic Games, Inc.
// SPDX-License-Identifier: MIT
// This file has been generated by the ApiGear Code Generator.
// Do not edit. Changes will be lost when the code is re-generated.
#include "TbSame2Settings.h"
#include "TbSame2/Generated/TbSame2Factory.h"
#include "TbSame2/Generated/TbSame2LogCategories.h"
#include "ApiGearConnectionsStore.h"
#include "Engine/Engine.h"
#include "Misc/CoreDelegates.h"

UTbSame2Settings::UTbSame2Settings(const FObjectInitializer& ObjectInitializer)
	: Super(ObjectInitializer)
{
	FCoreDelegates::OnPostEngineInit.AddUObject(this, &UTbSame2Settings::ValidateSettingsPostEngineInit);
}

void UTbSame2Settings::ValidateSettingsPostEngineInit()
{
	check(GEngine);
	UApiGearConnectionsStore* AGCM = GEngine->GetEngineSubsystem<UApiGearConnectionsStore>();

	if (!AGCM->DoesConnectionExist(OLinkConnectionIdentifier))
	{
		UE_LOG(LogTbSame2, Warning, TEXT("UTbSame2Settings could not find connection %s."), *OLinkConnectionIdentifier);
		OLinkConnectionIdentifier = "";
	}

	// the local backend does not require configuration
	if (TracerServiceIdentifier == TbSame2LocalBackendIdentifier)
	{
		return;
	}

	if (!AGCM->DoesConnectionExist(TracerServiceIdentifier))
	{
		UE_LOG(LogTbSame2, Warning, TEXT("UTbSame2Settings could not find connection %s, falling back to local backend."), *TracerServiceIdentifier);
		TracerServiceIdentifier = TbSame2LocalBackendIdentifier;
	}
}

TScriptInterface<ITbSame2SameStruct1InterfaceInterface> UTbSame2Settings::GetITbSame2SameStruct1InterfaceInterfaceForLogging(FSubsystemCollectionBase& Collection)
{
	UTbSame2Settings* TbSame2Settings = GetMutableDefault<UTbSame2Settings>();

	FString BackendIdentifier = TbSame2Settings->TracerServiceIdentifier;

	if (TbSame2Settings->TracerServiceIdentifier == TbSame2LocalBackendIdentifier)
	{
		return FTbSame2ModuleFactory::GetTbSame2SameStruct1InterfaceImplementation(TbSame2LocalBackendIdentifier, Collection);
	}

	if (TbSame2Settings->TracerServiceIdentifier != TbSame2LocalBackendIdentifier)
	{
		return FTbSame2ModuleFactory::GetTbSame2SameStruct1InterfaceImplementation("olink", Collection);
	}

	return nullptr;
}

TScriptInterface<ITbSame2SameStruct2InterfaceInterface> UTbSame2Settings::GetITbSame2SameStruct2InterfaceInterfaceForLogging(FSubsystemCollectionBase& Collection)
{
	UTbSame2Settings* TbSame2Settings = GetMutableDefault<UTbSame2Settings>();

	FString BackendIdentifier = TbSame2Settings->TracerServiceIdentifier;

	if (TbSame2Settings->TracerServiceIdentifier == TbSame2LocalBackendIdentifier)
	{
		return FTbSame2ModuleFactory::GetTbSame2SameStruct2InterfaceImplementation(TbSame2LocalBackendIdentifier, Collection);
	}

	if (TbSame2Settings->TracerServiceIdentifier != TbSame2LocalBackendIdentifier)
	{
		return FTbSame2ModuleFactory::GetTbSame2SameStruct2InterfaceImplementation("olink", Collection);
	}

	return nullptr;
}

TScriptInterface<ITbSame2SameEnum1InterfaceInterface> UTbSame2Settings::GetITbSame2SameEnum1InterfaceInterfaceForLogging(FSubsystemCollectionBase& Collection)
{
	UTbSame2Settings* TbSame2Settings = GetMutableDefault<UTbSame2Settings>();

	FString BackendIdentifier = TbSame2Settings->TracerServiceIdentifier;

	if (TbSame2Settings->TracerServiceIdentifier == TbSame2LocalBackendIdentifier)
	{
		return FTbSame2ModuleFactory::GetTbSame2SameEnum1InterfaceImplementation(TbSame2LocalBackendIdentifier, Collection);
	}

	if (TbSame2Settings->TracerServiceIdentifier != TbSame2LocalBackendIdentifier)
	{
		return FTbSame2ModuleFactory::GetTbSame2SameEnum1InterfaceImplementation("olink", Collection);
	}

	return nullptr;
}

TScriptInterface<ITbSame2SameEnum2InterfaceInterface> UTbSame2Settings::GetITbSame2SameEnum2InterfaceInterfaceForLogging(FSubsystemCollectionBase& Collection)
{
	UTbSame2Settings* TbSame2Settings = GetMutableDefault<UTbSame2Settings>();

	FString BackendIdentifier = TbSame2Settings->TracerServiceIdentifier;

	if (TbSame2Settings->TracerServiceIdentifier == TbSame2LocalBackendIdentifier)
	{
		return FTbSame2ModuleFactory::GetTbSame2SameEnum2InterfaceImplementation(TbSame2LocalBackendIdentifier, Collection);
	}

	if (TbSame2Settings->TracerServiceIdentifier != TbSame2LocalBackendIdentifier)
	{
		return FTbSame2ModuleFactory::GetTbSame2SameEnum2InterfaceImplementation("olink", Collection);
	}

	return nullptr;
}
