// SPDX-FileCopyrightText: Copyright ApiGear UG and Epic Games, Inc.
// SPDX-License-Identifier: MIT
// This file has been generated by the ApiGear Code Generator.
// Do not edit. Changes will be lost when the code is re-generated.

#include "TbSame1Core.h"
#include "TbSame1/Generated/TbSame1Factory.h"
#include "Engine/Engine.h"
#include "TbSame1Settings.h"
#include "Modules/ModuleManager.h"

#define LOCTEXT_NAMESPACE "TbSame1Core"

void FTbSame1CoreModule::StartupModule()
{
}

void FTbSame1CoreModule::ShutdownModule()
{
	// This function may be called during shutdown to clean up your module.  For modules that support dynamic reloading,
	// we call this function before unloading the module.
}

IMPLEMENT_MODULE(FTbSame1CoreModule, TbSame1Core)

#undef LOCTEXT_NAMESPACE
