// SPDX-FileCopyrightText: Copyright ApiGear UG and Epic Games, Inc.
// SPDX-License-Identifier: MIT
// This file has been generated by the ApiGear Code Generator.
// Do not edit. Changes will be lost when the code is re-generated.
#include "TbEnumSettings.h"
#include "TbEnum/Generated/TbEnumFactory.h"
#include "TbEnum/Generated/TbEnumLogCategories.h"
#include "ApiGearConnectionsStore.h"
#include "Engine/Engine.h"
#include "Misc/CoreDelegates.h"

UTbEnumSettings::UTbEnumSettings(const FObjectInitializer& ObjectInitializer)
	: Super(ObjectInitializer)
{
	FCoreDelegates::OnPostEngineInit.AddUObject(this, &UTbEnumSettings::ValidateSettingsPostEngineInit);
}

void UTbEnumSettings::ValidateSettingsPostEngineInit()
{
	check(GEngine);
	UApiGearConnectionsStore* AGCM = GEngine->GetEngineSubsystem<UApiGearConnectionsStore>();

	if (!AGCM->DoesConnectionExist(OLinkConnectionIdentifier))
	{
		UE_LOG(LogTbEnum, Warning, TEXT("UTbEnumSettings could not find connection %s."), *OLinkConnectionIdentifier);
		OLinkConnectionIdentifier = "";
	}

	// the local backend does not require configuration
	if (TracerServiceIdentifier == TbEnumLocalBackendIdentifier)
	{
		return;
	}

	if (!AGCM->DoesConnectionExist(TracerServiceIdentifier))
	{
		UE_LOG(LogTbEnum, Warning, TEXT("UTbEnumSettings could not find connection %s, falling back to local backend."), *TracerServiceIdentifier);
		TracerServiceIdentifier = TbEnumLocalBackendIdentifier;
	}
}

TScriptInterface<ITbEnumEnumInterfaceInterface> UTbEnumSettings::GetITbEnumEnumInterfaceInterfaceForLogging(FSubsystemCollectionBase& Collection)
{
	UTbEnumSettings* TbEnumSettings = GetMutableDefault<UTbEnumSettings>();

	FString BackendIdentifier = TbEnumSettings->TracerServiceIdentifier;

	if (TbEnumSettings->TracerServiceIdentifier == TbEnumLocalBackendIdentifier)
	{
		return FTbEnumModuleFactory::GetTbEnumEnumInterfaceImplementation(TbEnumLocalBackendIdentifier, Collection);
	}

	if (TbEnumSettings->TracerServiceIdentifier != TbEnumLocalBackendIdentifier)
	{
		return FTbEnumModuleFactory::GetTbEnumEnumInterfaceImplementation("olink", Collection);
	}

	return nullptr;
}
