// SPDX-FileCopyrightText: Copyright ApiGear UG and Epic Games, Inc.
// SPDX-License-Identifier: MIT
// This file has been generated by the ApiGear Code Generator.
// Do not edit. Changes will be lost when the code is re-generated.
#include "TbSame1/Tests/TbSame1TestsCommon.h"
#include "TbSame1/Generated/api/TbSame1_data.h"
#include "Misc/AutomationTest.h"

#if WITH_DEV_AUTOMATION_TESTS
FTbSame1Struct1 createTestFTbSame1Struct1()
{
	FTbSame1Struct1 TestValue;

	TestValue.field1 = 1;
	TestValue.field2 = 1;
	TestValue.field3 = 1;

	return TestValue;
}

TArray<FTbSame1Struct1> createTestFTbSame1Struct1Array()
{
	TArray<FTbSame1Struct1> TestValueArray;

	TestValueArray.Add(createTestFTbSame1Struct1());

	return TestValueArray;
}

FTbSame1Struct2 createTestFTbSame1Struct2()
{
	FTbSame1Struct2 TestValue;

	TestValue.field1 = 1;
	TestValue.field2 = 1;
	TestValue.field3 = 1;

	return TestValue;
}

TArray<FTbSame1Struct2> createTestFTbSame1Struct2Array()
{
	TArray<FTbSame1Struct2> TestValueArray;

	TestValueArray.Add(createTestFTbSame1Struct2());

	return TestValueArray;
}

TArray<ETbSame1Enum1> createTestFTbSame1Enum1Array()
{
	TArray<ETbSame1Enum1> TestValueArray;

	ETbSame1Enum1 val = ETbSame1Enum1::TS1E1_Value1;
	TestValueArray.Add(val);
	return TestValueArray;
}


TArray<ETbSame1Enum2> createTestFTbSame1Enum2Array()
{
	TArray<ETbSame1Enum2> TestValueArray;

	ETbSame1Enum2 val = ETbSame1Enum2::TS1E2_Value1;
	TestValueArray.Add(val);
	return TestValueArray;
}



#endif // WITH_DEV_AUTOMATION_TESTS
