// SPDX-FileCopyrightText: Copyright ApiGear UG and Epic Games, Inc.
// SPDX-License-Identifier: MIT
// This file has been generated by the ApiGear Code Generator.
// Do not edit. Changes will be lost when the code is re-generated.
#pragma once

#include "TbSame1/Generated/api/TbSame1_data.h"
#include "Runtime/Launch/Resources/Version.h"
#include "Misc/AutomationTest.h"

#if WITH_DEV_AUTOMATION_TESTS

#if (ENGINE_MAJOR_VERSION >= 5)
#if (ENGINE_MINOR_VERSION >= 5)
inline constexpr EAutomationTestFlags TbSame1TestFilterMask = EAutomationTestFlags_ApplicationContextMask | EAutomationTestFlags::ProductFilter;
#else
inline constexpr int TbSame1TestFilterMask = EAutomationTestFlags::ApplicationContextMask | EAutomationTestFlags::ProductFilter;
#endif
#else
constexpr int TbSame1TestFilterMask = EAutomationTestFlags::ApplicationContextMask | EAutomationTestFlags::ProductFilter;
#endif

FTbSame1Struct1 TBSAME1CORE_API createTestFTbSame1Struct1();

TArray<FTbSame1Struct1> TBSAME1CORE_API createTestFTbSame1Struct1Array();

FTbSame1Struct2 TBSAME1CORE_API createTestFTbSame1Struct2();

TArray<FTbSame1Struct2> TBSAME1CORE_API createTestFTbSame1Struct2Array();

TArray<ETbSame1Enum1> TBSAME1CORE_API createTestFTbSame1Enum1Array();

TArray<ETbSame1Enum2> TBSAME1CORE_API createTestFTbSame1Enum2Array();

#endif // WITH_DEV_AUTOMATION_TESTS
