// SPDX-FileCopyrightText: Copyright ApiGear UG and Epic Games, Inc.
// SPDX-License-Identifier: MIT
// This file has been generated by the ApiGear Code Generator.
// Do not edit. Changes will be lost when the code is re-generated.
#pragma once

#include "Testbed2/Generated/api/Testbed2_data.h"
#include "Runtime/Launch/Resources/Version.h"
#include "Misc/AutomationTest.h"

#if WITH_DEV_AUTOMATION_TESTS

#if (ENGINE_MAJOR_VERSION >= 5)
#if (ENGINE_MINOR_VERSION >= 5)
inline constexpr EAutomationTestFlags Testbed2TestFilterMask = EAutomationTestFlags_ApplicationContextMask | EAutomationTestFlags::ProductFilter;
#else
inline constexpr int Testbed2TestFilterMask = EAutomationTestFlags::ApplicationContextMask | EAutomationTestFlags::ProductFilter;
#endif
#else
constexpr int Testbed2TestFilterMask = EAutomationTestFlags::ApplicationContextMask | EAutomationTestFlags::ProductFilter;
#endif

FTestbed2Struct1 TESTBED2CORE_API createTestFTestbed2Struct1();

TArray<FTestbed2Struct1> TESTBED2CORE_API createTestFTestbed2Struct1Array();

FTestbed2Struct2 TESTBED2CORE_API createTestFTestbed2Struct2();

TArray<FTestbed2Struct2> TESTBED2CORE_API createTestFTestbed2Struct2Array();

FTestbed2Struct3 TESTBED2CORE_API createTestFTestbed2Struct3();

TArray<FTestbed2Struct3> TESTBED2CORE_API createTestFTestbed2Struct3Array();

FTestbed2Struct4 TESTBED2CORE_API createTestFTestbed2Struct4();

TArray<FTestbed2Struct4> TESTBED2CORE_API createTestFTestbed2Struct4Array();

FTestbed2NestedStruct1 TESTBED2CORE_API createTestFTestbed2NestedStruct1();

TArray<FTestbed2NestedStruct1> TESTBED2CORE_API createTestFTestbed2NestedStruct1Array();

FTestbed2NestedStruct2 TESTBED2CORE_API createTestFTestbed2NestedStruct2();

TArray<FTestbed2NestedStruct2> TESTBED2CORE_API createTestFTestbed2NestedStruct2Array();

FTestbed2NestedStruct3 TESTBED2CORE_API createTestFTestbed2NestedStruct3();

TArray<FTestbed2NestedStruct3> TESTBED2CORE_API createTestFTestbed2NestedStruct3Array();

TArray<ETestbed2Enum1> TESTBED2CORE_API createTestFTestbed2Enum1Array();

TArray<ETestbed2Enum2> TESTBED2CORE_API createTestFTestbed2Enum2Array();

TArray<ETestbed2Enum3> TESTBED2CORE_API createTestFTestbed2Enum3Array();

#endif // WITH_DEV_AUTOMATION_TESTS
