// SPDX-FileCopyrightText: Copyright ApiGear UG and Epic Games, Inc.
// SPDX-License-Identifier: MIT
// This file has been generated by the ApiGear Code Generator.
// Do not edit. Changes will be lost when the code is re-generated.
#pragma once

#include "CoreMinimal.h"
#include "UObject/ObjectMacros.h"
#include "UObject/Object.h"
#include "Engine/EngineTypes.h"
#include "TbSimpleSettings.generated.h"

const FString TbSimpleLocalBackendIdentifier = "Local";

class FSubsystemCollectionBase;
class ITbSimpleVoidInterfaceInterface;
class ITbSimpleSimpleInterfaceInterface;
class ITbSimpleSimpleArrayInterfaceInterface;
class ITbSimpleNoPropertiesInterfaceInterface;
class ITbSimpleNoOperationsInterfaceInterface;
class ITbSimpleNoSignalsInterfaceInterface;
class ITbSimpleEmptyInterfaceInterface;

/**
 * Implements the settings for the TbSimple plugin.
 */
UCLASS(Config = Engine, DefaultConfig)
class TBSIMPLECORE_API UTbSimpleSettings : public UObject
{
	GENERATED_BODY()

	UTbSimpleSettings(const FObjectInitializer& ObjectInitializer);

public:
	/** Callback used to validate the settings once the engine is available */
	void ValidateSettingsPostEngineInit();

	/** Choose the backend service for the logging decorator to use */
	UPROPERTY(EditAnywhere, config, Category = TracerServiceSetup)
	FString TracerServiceIdentifier;

	/** Choose the olink connection to use */
	UPROPERTY(EditAnywhere, config, Category = OLinkConnectionSetup)
	FString OLinkConnectionIdentifier;
	static TScriptInterface<ITbSimpleVoidInterfaceInterface> GetITbSimpleVoidInterfaceInterfaceForLogging(FSubsystemCollectionBase& Collection);
	static TScriptInterface<ITbSimpleSimpleInterfaceInterface> GetITbSimpleSimpleInterfaceInterfaceForLogging(FSubsystemCollectionBase& Collection);
	static TScriptInterface<ITbSimpleSimpleArrayInterfaceInterface> GetITbSimpleSimpleArrayInterfaceInterfaceForLogging(FSubsystemCollectionBase& Collection);
	static TScriptInterface<ITbSimpleNoPropertiesInterfaceInterface> GetITbSimpleNoPropertiesInterfaceInterfaceForLogging(FSubsystemCollectionBase& Collection);
	static TScriptInterface<ITbSimpleNoOperationsInterfaceInterface> GetITbSimpleNoOperationsInterfaceInterfaceForLogging(FSubsystemCollectionBase& Collection);
	static TScriptInterface<ITbSimpleNoSignalsInterfaceInterface> GetITbSimpleNoSignalsInterfaceInterfaceForLogging(FSubsystemCollectionBase& Collection);
	static TScriptInterface<ITbSimpleEmptyInterfaceInterface> GetITbSimpleEmptyInterfaceInterfaceForLogging(FSubsystemCollectionBase& Collection);

	/** Choose the heartbeat interval in milliseconds for the msgbus connection on the service side.
	 * On the service side this adjusts the heartbeat between client and service. The clients will receive the value from service.
	 * On the client side this adjusts how often discovery messages are sent until a service is connected.
	 */
	UPROPERTY(EditAnywhere, config, Category = MsgBusConnectionSetup, meta = (DisplayName = "Heartbeat interval (in milliseconds)"))
	uint32 MsgBusHeartbeatIntervalMS = 200;
};
