// SPDX-FileCopyrightText: Copyright ApiGear UG and Epic Games, Inc.
// SPDX-License-Identifier: MIT
// This file has been generated by the ApiGear Code Generator.
// Do not edit. Changes will be lost when the code is re-generated.
#pragma once

#include "TbEnum/Generated/api/TbEnum_data.h"
#include "Runtime/Launch/Resources/Version.h"
#include "Misc/AutomationTest.h"

#if WITH_DEV_AUTOMATION_TESTS

#if (ENGINE_MAJOR_VERSION >= 5)
#if (ENGINE_MINOR_VERSION >= 5)
inline constexpr EAutomationTestFlags TbEnumTestFilterMask = EAutomationTestFlags_ApplicationContextMask | EAutomationTestFlags::ProductFilter;
#else
inline constexpr int TbEnumTestFilterMask = EAutomationTestFlags::ApplicationContextMask | EAutomationTestFlags::ProductFilter;
#endif
#else
constexpr int TbEnumTestFilterMask = EAutomationTestFlags::ApplicationContextMask | EAutomationTestFlags::ProductFilter;
#endif

TArray<ETbEnumEnum0> TBENUMCORE_API createTestFTbEnumEnum0Array();

TArray<ETbEnumEnum1> TBENUMCORE_API createTestFTbEnumEnum1Array();

TArray<ETbEnumEnum2> TBENUMCORE_API createTestFTbEnumEnum2Array();

TArray<ETbEnumEnum3> TBENUMCORE_API createTestFTbEnumEnum3Array();

#endif // WITH_DEV_AUTOMATION_TESTS
