// SPDX-FileCopyrightText: Copyright ApiGear UG and Epic Games, Inc.
// SPDX-License-Identifier: MIT
// This file has been generated by the ApiGear Code Generator.
// Do not edit. Changes will be lost when the code is re-generated.

#include "CounterEditor.h"
#include "ISettingsModule.h"
#include "PropertyEditorModule.h"
#include "CounterSettings.h"
#include "CounterConnectionSettings.h"

#define LOCTEXT_NAMESPACE "CounterEditor"

void FCounterEditorModule::StartupModule()
{
	// register settings
	ISettingsModule* SettingsModule = FModuleManager::GetModulePtr<ISettingsModule>("Settings");

	if (SettingsModule != nullptr)
	{
		SettingsModule->RegisterSettings("Project", "Plugins", "ApiGear Counter", LOCTEXT("CounterSettingsName", "ApiGear Counter"), LOCTEXT("CounterSettingsDescription", "Project settings for ApiGear Counter plugin"), GetMutableDefault<UCounterSettings>());
	}

	// register details customization
	FPropertyEditorModule& PropertyModule = FModuleManager::LoadModuleChecked<FPropertyEditorModule>(TEXT("PropertyEditor"));
	PropertyModule.RegisterCustomClassLayout("CounterSettings", FOnGetDetailCustomizationInstance::CreateStatic(&FCounterConnectionSettingsDetails::MakeInstance));
}

void FCounterEditorModule::ShutdownModule()
{
	// unregister settings
	ISettingsModule* SettingsModule = FModuleManager::GetModulePtr<ISettingsModule>("Settings");

	if (SettingsModule != nullptr)
	{
		SettingsModule->UnregisterSettings("Project", "Plugins", "ApiGear Counter");
	}
}

IMPLEMENT_MODULE(FCounterEditorModule, CounterEditor)

#undef LOCTEXT_NAMESPACE
