// SPDX-FileCopyrightText: Copyright ApiGear UG and Epic Games, Inc.
// SPDX-License-Identifier: MIT
// This file has been generated by the ApiGear Code Generator.
// Do not edit. Changes will be lost when the code is re-generated.
#pragma once

#include "IDetailCustomization.h"
#include "Templates/SharedPointer.h"

class IDetailLayoutBuilder;
class IPropertyHandle;
class SWidget;

/**
 * Provides the dropdown menu for the connection settings per module
 */
class FTbNamesConnectionSettingsDetails : public IDetailCustomization
{
public:
	/** Makes a new instance of this detail layout class for a specific detail view requesting it */
	static TSharedRef<IDetailCustomization> MakeInstance();

	/** IDetailCustomization interface */
	virtual void CustomizeDetails(IDetailLayoutBuilder& DetailBuilder) override;

private:
	void CustomizeTracerDetails(IDetailLayoutBuilder& DetailBuilder);
	TSharedRef<SWidget> MakeDefaultBackendServiceSelectorWidget(const TSharedPtr<IPropertyHandle>& PropertyHandle);
	TSharedPtr<FText> SelectedDefaultBackendService;
	TArray<TSharedPtr<FText>> AvailableServices;

	void CustomizeOLinkDetails(IDetailLayoutBuilder& DetailBuilder);
	TSharedRef<SWidget> MakeDefaultOLinkConnectionSelectorWidget(const TSharedPtr<IPropertyHandle>& PropertyHandle);
	TSharedPtr<FText> SelectedDefaultOLinkConnection;
	TArray<TSharedPtr<FText>> AvailableOLinkConnections;
};
