// SPDX-FileCopyrightText: Copyright ApiGear UG and Epic Games, Inc.
// SPDX-License-Identifier: MIT
// This file has been generated by the ApiGear Code Generator.
// Do not edit. Changes will be lost when the code is re-generated.
#include "TbRefIfacesSettings.h"
#include "TbRefIfaces/Generated/TbRefIfacesFactory.h"
#include "TbRefIfaces/Generated/TbRefIfacesLogCategories.h"
#include "ApiGearConnectionsStore.h"
#include "Engine/Engine.h"
#include "Misc/CoreDelegates.h"

UTbRefIfacesSettings::UTbRefIfacesSettings(const FObjectInitializer& ObjectInitializer)
	: Super(ObjectInitializer)
{
#if ENGINE_MAJOR_VERSION >= 5 && ENGINE_MINOR_VERSION >= 8
	FCoreDelegates::GetOnPostEngineInit().AddUObject(this, &UTbRefIfacesSettings::ValidateSettingsPostEngineInit);
#else
	FCoreDelegates::OnPostEngineInit.AddUObject(this, &UTbRefIfacesSettings::ValidateSettingsPostEngineInit);
#endif
}

void UTbRefIfacesSettings::ValidateSettingsPostEngineInit()
{
	check(GEngine);
	UApiGearConnectionsStore* AGCM = GEngine->GetEngineSubsystem<UApiGearConnectionsStore>();

	if (!AGCM->DoesConnectionExist(OLinkConnectionIdentifier))
	{
		UE_LOG(LogTbRefIfaces, Warning, TEXT("UTbRefIfacesSettings could not find connection %s."), *OLinkConnectionIdentifier);
		OLinkConnectionIdentifier = "";
	}

	// the local backend does not require configuration
	if (TracerServiceIdentifier == TbRefIfacesLocalBackendIdentifier)
	{
		return;
	}

	if (!AGCM->DoesConnectionExist(TracerServiceIdentifier))
	{
		UE_LOG(LogTbRefIfaces, Warning, TEXT("UTbRefIfacesSettings could not find connection %s, falling back to local backend."), *TracerServiceIdentifier);
		TracerServiceIdentifier = TbRefIfacesLocalBackendIdentifier;
	}
}

TScriptInterface<ITbRefIfacesSimpleLocalIfInterface> UTbRefIfacesSettings::GetITbRefIfacesSimpleLocalIfInterfaceForLogging(FSubsystemCollectionBase& Collection)
{
	UTbRefIfacesSettings* TbRefIfacesSettings = GetMutableDefault<UTbRefIfacesSettings>();

	FString BackendIdentifier = TbRefIfacesSettings->TracerServiceIdentifier;

	if (TbRefIfacesSettings->TracerServiceIdentifier == TbRefIfacesLocalBackendIdentifier)
	{
		return FTbRefIfacesModuleFactory::GetTbRefIfacesSimpleLocalIfImplementation(TbRefIfacesLocalBackendIdentifier, Collection);
	}

	if (TbRefIfacesSettings->TracerServiceIdentifier != TbRefIfacesLocalBackendIdentifier)
	{
		return FTbRefIfacesModuleFactory::GetTbRefIfacesSimpleLocalIfImplementation("olink", Collection);
	}

	return nullptr;
}

TScriptInterface<ITbRefIfacesParentIfInterface> UTbRefIfacesSettings::GetITbRefIfacesParentIfInterfaceForLogging(FSubsystemCollectionBase& Collection)
{
	UTbRefIfacesSettings* TbRefIfacesSettings = GetMutableDefault<UTbRefIfacesSettings>();

	FString BackendIdentifier = TbRefIfacesSettings->TracerServiceIdentifier;

	if (TbRefIfacesSettings->TracerServiceIdentifier == TbRefIfacesLocalBackendIdentifier)
	{
		return FTbRefIfacesModuleFactory::GetTbRefIfacesParentIfImplementation(TbRefIfacesLocalBackendIdentifier, Collection);
	}

	if (TbRefIfacesSettings->TracerServiceIdentifier != TbRefIfacesLocalBackendIdentifier)
	{
		return FTbRefIfacesModuleFactory::GetTbRefIfacesParentIfImplementation("olink", Collection);
	}

	return nullptr;
}
