// SPDX-FileCopyrightText: Copyright ApiGear UG and Epic Games, Inc.
// SPDX-License-Identifier: MIT
// This file has been generated by the ApiGear Code Generator.
// Do not edit. Changes will be lost when the code is re-generated.

#include "TbRefIfacesEditor.h"
#include "ISettingsModule.h"
#include "PropertyEditorModule.h"
#include "TbRefIfacesSettings.h"
#include "TbRefIfacesConnectionSettings.h"

#define LOCTEXT_NAMESPACE "TbRefIfacesEditor"

void FTbRefIfacesEditorModule::StartupModule()
{
	// register settings
	ISettingsModule* SettingsModule = FModuleManager::GetModulePtr<ISettingsModule>("Settings");

	if (SettingsModule != nullptr)
	{
		SettingsModule->RegisterSettings("Project", "Plugins", "ApiGear TbRefIfaces", LOCTEXT("TbRefIfacesSettingsName", "ApiGear TbRefIfaces"), LOCTEXT("TbRefIfacesSettingsDescription", "Project settings for ApiGear TbRefIfaces plugin"), GetMutableDefault<UTbRefIfacesSettings>());
	}

	// register details customization
	FPropertyEditorModule& PropertyModule = FModuleManager::LoadModuleChecked<FPropertyEditorModule>(TEXT("PropertyEditor"));
	PropertyModule.RegisterCustomClassLayout("TbRefIfacesSettings", FOnGetDetailCustomizationInstance::CreateStatic(&FTbRefIfacesConnectionSettingsDetails::MakeInstance));
}

void FTbRefIfacesEditorModule::ShutdownModule()
{
	// unregister settings
	ISettingsModule* SettingsModule = FModuleManager::GetModulePtr<ISettingsModule>("Settings");

	if (SettingsModule != nullptr)
	{
		SettingsModule->UnregisterSettings("Project", "Plugins", "ApiGear TbRefIfaces");
	}
}

IMPLEMENT_MODULE(FTbRefIfacesEditorModule, TbRefIfacesEditor)

#undef LOCTEXT_NAMESPACE
