// SPDX-FileCopyrightText: Copyright ApiGear UG and Epic Games, Inc.
// SPDX-License-Identifier: MIT
// This file has been generated by the ApiGear Code Generator.
// Do not edit. Changes will be lost when the code is re-generated.
#pragma once

#include "CoreMinimal.h"
#include "UObject/ObjectMacros.h"
#include "UObject/Object.h"
#include "Engine/EngineTypes.h"
#include "TbSame1Settings.generated.h"

const FString TbSame1LocalBackendIdentifier = "Local";

class FSubsystemCollectionBase;
class ITbSame1SameStruct1InterfaceInterface;
class ITbSame1SameStruct2InterfaceInterface;
class ITbSame1SameEnum1InterfaceInterface;
class ITbSame1SameEnum2InterfaceInterface;

/**
 * Implements the settings for the TbSame1 plugin.
 */
UCLASS(Config = Engine, DefaultConfig)
class TBSAME1CORE_API UTbSame1Settings : public UObject
{
	GENERATED_BODY()

	UTbSame1Settings(const FObjectInitializer& ObjectInitializer);

public:
	/** Callback used to validate the settings once the engine is available */
	void ValidateSettingsPostEngineInit();

	/** Choose the backend service for the logging decorator to use */
	UPROPERTY(EditAnywhere, config, Category = TracerServiceSetup)
	FString TracerServiceIdentifier;

	/** Choose the olink connection to use */
	UPROPERTY(EditAnywhere, config, Category = OLinkConnectionSetup)
	FString OLinkConnectionIdentifier;
	static TScriptInterface<ITbSame1SameStruct1InterfaceInterface> GetITbSame1SameStruct1InterfaceInterfaceForLogging(FSubsystemCollectionBase& Collection);
	static TScriptInterface<ITbSame1SameStruct2InterfaceInterface> GetITbSame1SameStruct2InterfaceInterfaceForLogging(FSubsystemCollectionBase& Collection);
	static TScriptInterface<ITbSame1SameEnum1InterfaceInterface> GetITbSame1SameEnum1InterfaceInterfaceForLogging(FSubsystemCollectionBase& Collection);
	static TScriptInterface<ITbSame1SameEnum2InterfaceInterface> GetITbSame1SameEnum2InterfaceInterfaceForLogging(FSubsystemCollectionBase& Collection);

	/** Choose the heartbeat interval in milliseconds for the msgbus connection on the service side.
	 * On the service side this adjusts the heartbeat between client and service. The clients will receive the value from service.
	 * On the client side this adjusts how often discovery messages are sent until a service is connected.
	 */
	UPROPERTY(EditAnywhere, config, Category = MsgBusConnectionSetup, meta = (DisplayName = "Heartbeat interval (in milliseconds)"))
	uint32 MsgBusHeartbeatIntervalMS = 200;
};
