// SPDX-FileCopyrightText: Copyright ApiGear UG and Epic Games, Inc.
// SPDX-License-Identifier: MIT
// This file has been generated by the ApiGear Code Generator.
// Do not edit. Changes will be lost when the code is re-generated.

#include "TbNamesCore.h"
#include "TbNames/Generated/TbNamesFactory.h"
#include "Engine/Engine.h"
#include "TbNamesSettings.h"
#include "Modules/ModuleManager.h"

#define LOCTEXT_NAMESPACE "TbNamesCore"

void FTbNamesCoreModule::StartupModule()
{
}

void FTbNamesCoreModule::ShutdownModule()
{
	// This function may be called during shutdown to clean up your module.  For modules that support dynamic reloading,
	// we call this function before unloading the module.
}

IMPLEMENT_MODULE(FTbNamesCoreModule, TbNamesCore)

#undef LOCTEXT_NAMESPACE
