// SPDX-FileCopyrightText: Copyright ApiGear UG and Epic Games, Inc.
// SPDX-License-Identifier: MIT
// This file has been generated by the ApiGear Code Generator.
// Do not edit. Changes will be lost when the code is re-generated.
#include "TbNamesSettings.h"
#include "TbNames/Generated/TbNamesFactory.h"
#include "TbNames/Generated/TbNamesLogCategories.h"
#include "ApiGearConnectionsStore.h"
#include "Engine/Engine.h"
#include "Misc/CoreDelegates.h"

UTbNamesSettings::UTbNamesSettings(const FObjectInitializer& ObjectInitializer)
	: Super(ObjectInitializer)
{
	FCoreDelegates::OnPostEngineInit.AddUObject(this, &UTbNamesSettings::ValidateSettingsPostEngineInit);
}

void UTbNamesSettings::ValidateSettingsPostEngineInit()
{
	check(GEngine);
	UApiGearConnectionsStore* AGCM = GEngine->GetEngineSubsystem<UApiGearConnectionsStore>();

	if (!AGCM->DoesConnectionExist(OLinkConnectionIdentifier))
	{
		UE_LOG(LogTbNames, Warning, TEXT("UTbNamesSettings could not find connection %s."), *OLinkConnectionIdentifier);
		OLinkConnectionIdentifier = "";
	}

	// the local backend does not require configuration
	if (TracerServiceIdentifier == TbNamesLocalBackendIdentifier)
	{
		return;
	}

	if (!AGCM->DoesConnectionExist(TracerServiceIdentifier))
	{
		UE_LOG(LogTbNames, Warning, TEXT("UTbNamesSettings could not find connection %s, falling back to local backend."), *TracerServiceIdentifier);
		TracerServiceIdentifier = TbNamesLocalBackendIdentifier;
	}
}

TScriptInterface<ITbNamesNamEsInterface> UTbNamesSettings::GetITbNamesNamEsInterfaceForLogging(FSubsystemCollectionBase& Collection)
{
	UTbNamesSettings* TbNamesSettings = GetMutableDefault<UTbNamesSettings>();

	FString BackendIdentifier = TbNamesSettings->TracerServiceIdentifier;

	if (TbNamesSettings->TracerServiceIdentifier == TbNamesLocalBackendIdentifier)
	{
		return FTbNamesModuleFactory::GetTbNamesNamEsImplementation(TbNamesLocalBackendIdentifier, Collection);
	}

	if (TbNamesSettings->TracerServiceIdentifier != TbNamesLocalBackendIdentifier)
	{
		return FTbNamesModuleFactory::GetTbNamesNamEsImplementation("olink", Collection);
	}

	return nullptr;
}
