// SPDX-FileCopyrightText: Copyright ApiGear UG and Epic Games, Inc.
// SPDX-License-Identifier: MIT
// This file has been generated by the ApiGear Code Generator.
// Do not edit. Changes will be lost when the code is re-generated.
#pragma once

#include "Testbed1/Generated/api/Testbed1_data.h"
#include "Runtime/Launch/Resources/Version.h"
#include "Misc/AutomationTest.h"

#if WITH_DEV_AUTOMATION_TESTS

#if (ENGINE_MAJOR_VERSION >= 5)
#if (ENGINE_MINOR_VERSION >= 5)
inline constexpr EAutomationTestFlags Testbed1TestFilterMask = EAutomationTestFlags_ApplicationContextMask | EAutomationTestFlags::ProductFilter;
#else
inline constexpr int Testbed1TestFilterMask = EAutomationTestFlags::ApplicationContextMask | EAutomationTestFlags::ProductFilter;
#endif
#else
constexpr int Testbed1TestFilterMask = EAutomationTestFlags::ApplicationContextMask | EAutomationTestFlags::ProductFilter;
#endif

FTestbed1StructBool TESTBED1CORE_API createTestFTestbed1StructBool();

TArray<FTestbed1StructBool> TESTBED1CORE_API createTestFTestbed1StructBoolArray();

FTestbed1StructInt TESTBED1CORE_API createTestFTestbed1StructInt();

TArray<FTestbed1StructInt> TESTBED1CORE_API createTestFTestbed1StructIntArray();

FTestbed1StructFloat TESTBED1CORE_API createTestFTestbed1StructFloat();

TArray<FTestbed1StructFloat> TESTBED1CORE_API createTestFTestbed1StructFloatArray();

FTestbed1StructString TESTBED1CORE_API createTestFTestbed1StructString();

TArray<FTestbed1StructString> TESTBED1CORE_API createTestFTestbed1StructStringArray();

FTestbed1StructStruct TESTBED1CORE_API createTestFTestbed1StructStruct();

TArray<FTestbed1StructStruct> TESTBED1CORE_API createTestFTestbed1StructStructArray();

FTestbed1StructEnum TESTBED1CORE_API createTestFTestbed1StructEnum();

TArray<FTestbed1StructEnum> TESTBED1CORE_API createTestFTestbed1StructEnumArray();

FTestbed1StructBoolWithArray TESTBED1CORE_API createTestFTestbed1StructBoolWithArray();

TArray<FTestbed1StructBoolWithArray> TESTBED1CORE_API createTestFTestbed1StructBoolWithArrayArray();

FTestbed1StructIntWithArray TESTBED1CORE_API createTestFTestbed1StructIntWithArray();

TArray<FTestbed1StructIntWithArray> TESTBED1CORE_API createTestFTestbed1StructIntWithArrayArray();

FTestbed1StructFloatWithArray TESTBED1CORE_API createTestFTestbed1StructFloatWithArray();

TArray<FTestbed1StructFloatWithArray> TESTBED1CORE_API createTestFTestbed1StructFloatWithArrayArray();

FTestbed1StructStringWithArray TESTBED1CORE_API createTestFTestbed1StructStringWithArray();

TArray<FTestbed1StructStringWithArray> TESTBED1CORE_API createTestFTestbed1StructStringWithArrayArray();

FTestbed1StructStructWithArray TESTBED1CORE_API createTestFTestbed1StructStructWithArray();

TArray<FTestbed1StructStructWithArray> TESTBED1CORE_API createTestFTestbed1StructStructWithArrayArray();

FTestbed1StructEnumWithArray TESTBED1CORE_API createTestFTestbed1StructEnumWithArray();

TArray<FTestbed1StructEnumWithArray> TESTBED1CORE_API createTestFTestbed1StructEnumWithArrayArray();

TArray<ETestbed1Enum0> TESTBED1CORE_API createTestFTestbed1Enum0Array();

#endif // WITH_DEV_AUTOMATION_TESTS
