// SPDX-FileCopyrightText: Copyright ApiGear UG and Epic Games, Inc.
// SPDX-License-Identifier: MIT
// This file has been generated by the ApiGear Code Generator.
// Do not edit. Changes will be lost when the code is re-generated.
#include "Testbed1Settings.h"
#include "Testbed1/Generated/Testbed1Factory.h"
#include "Testbed1/Generated/Testbed1LogCategories.h"
#include "ApiGearConnectionsStore.h"
#include "Engine/Engine.h"
#include "Misc/CoreDelegates.h"

UTestbed1Settings::UTestbed1Settings(const FObjectInitializer& ObjectInitializer)
	: Super(ObjectInitializer)
{
	FCoreDelegates::OnPostEngineInit.AddUObject(this, &UTestbed1Settings::ValidateSettingsPostEngineInit);
}

void UTestbed1Settings::ValidateSettingsPostEngineInit()
{
	check(GEngine);
	UApiGearConnectionsStore* AGCM = GEngine->GetEngineSubsystem<UApiGearConnectionsStore>();

	if (!AGCM->DoesConnectionExist(OLinkConnectionIdentifier))
	{
		UE_LOG(LogTestbed1, Warning, TEXT("UTestbed1Settings could not find connection %s."), *OLinkConnectionIdentifier);
		OLinkConnectionIdentifier = "";
	}

	// the local backend does not require configuration
	if (TracerServiceIdentifier == Testbed1LocalBackendIdentifier)
	{
		return;
	}

	if (!AGCM->DoesConnectionExist(TracerServiceIdentifier))
	{
		UE_LOG(LogTestbed1, Warning, TEXT("UTestbed1Settings could not find connection %s, falling back to local backend."), *TracerServiceIdentifier);
		TracerServiceIdentifier = Testbed1LocalBackendIdentifier;
	}
}

TScriptInterface<ITestbed1StructInterfaceInterface> UTestbed1Settings::GetITestbed1StructInterfaceInterfaceForLogging(FSubsystemCollectionBase& Collection)
{
	UTestbed1Settings* Testbed1Settings = GetMutableDefault<UTestbed1Settings>();

	FString BackendIdentifier = Testbed1Settings->TracerServiceIdentifier;

	if (Testbed1Settings->TracerServiceIdentifier == Testbed1LocalBackendIdentifier)
	{
		return FTestbed1ModuleFactory::GetTestbed1StructInterfaceImplementation(Testbed1LocalBackendIdentifier, Collection);
	}

	if (Testbed1Settings->TracerServiceIdentifier != Testbed1LocalBackendIdentifier)
	{
		return FTestbed1ModuleFactory::GetTestbed1StructInterfaceImplementation("olink", Collection);
	}

	return nullptr;
}

TScriptInterface<ITestbed1StructArrayInterfaceInterface> UTestbed1Settings::GetITestbed1StructArrayInterfaceInterfaceForLogging(FSubsystemCollectionBase& Collection)
{
	UTestbed1Settings* Testbed1Settings = GetMutableDefault<UTestbed1Settings>();

	FString BackendIdentifier = Testbed1Settings->TracerServiceIdentifier;

	if (Testbed1Settings->TracerServiceIdentifier == Testbed1LocalBackendIdentifier)
	{
		return FTestbed1ModuleFactory::GetTestbed1StructArrayInterfaceImplementation(Testbed1LocalBackendIdentifier, Collection);
	}

	if (Testbed1Settings->TracerServiceIdentifier != Testbed1LocalBackendIdentifier)
	{
		return FTestbed1ModuleFactory::GetTestbed1StructArrayInterfaceImplementation("olink", Collection);
	}

	return nullptr;
}

TScriptInterface<ITestbed1StructArray2InterfaceInterface> UTestbed1Settings::GetITestbed1StructArray2InterfaceInterfaceForLogging(FSubsystemCollectionBase& Collection)
{
	UTestbed1Settings* Testbed1Settings = GetMutableDefault<UTestbed1Settings>();

	FString BackendIdentifier = Testbed1Settings->TracerServiceIdentifier;

	if (Testbed1Settings->TracerServiceIdentifier == Testbed1LocalBackendIdentifier)
	{
		return FTestbed1ModuleFactory::GetTestbed1StructArray2InterfaceImplementation(Testbed1LocalBackendIdentifier, Collection);
	}

	if (Testbed1Settings->TracerServiceIdentifier != Testbed1LocalBackendIdentifier)
	{
		return FTestbed1ModuleFactory::GetTestbed1StructArray2InterfaceImplementation("olink", Collection);
	}

	return nullptr;
}
