// SPDX-FileCopyrightText: Copyright ApiGear UG and Epic Games, Inc.
// SPDX-License-Identifier: MIT
// This file has been generated by the ApiGear Code Generator.
// Do not edit. Changes will be lost when the code is re-generated.
#pragma once

#include "TbSame2/Generated/api/TbSame2_data.h"
#include "Runtime/Launch/Resources/Version.h"
#include "Misc/AutomationTest.h"

#if WITH_DEV_AUTOMATION_TESTS

#if (ENGINE_MAJOR_VERSION >= 5)
#if (ENGINE_MINOR_VERSION >= 5)
inline constexpr EAutomationTestFlags TbSame2TestFilterMask = EAutomationTestFlags_ApplicationContextMask | EAutomationTestFlags::ProductFilter;
#else
inline constexpr int TbSame2TestFilterMask = EAutomationTestFlags::ApplicationContextMask | EAutomationTestFlags::ProductFilter;
#endif
#else
constexpr int TbSame2TestFilterMask = EAutomationTestFlags::ApplicationContextMask | EAutomationTestFlags::ProductFilter;
#endif

FTbSame2Struct1 TBSAME2CORE_API createTestFTbSame2Struct1();

TArray<FTbSame2Struct1> TBSAME2CORE_API createTestFTbSame2Struct1Array();

FTbSame2Struct2 TBSAME2CORE_API createTestFTbSame2Struct2();

TArray<FTbSame2Struct2> TBSAME2CORE_API createTestFTbSame2Struct2Array();

#endif // WITH_DEV_AUTOMATION_TESTS
