// SPDX-FileCopyrightText: Copyright ApiGear UG and Epic Games, Inc.
// SPDX-License-Identifier: MIT
// This file has been generated by the ApiGear Code Generator.
// Do not edit. Changes will be lost when the code is re-generated.
#include "TbEnum/Tests/TbEnumTestsCommon.h"
#include "TbEnum/Generated/api/TbEnum_data.h"
#include "Misc/AutomationTest.h"

#if WITH_DEV_AUTOMATION_TESTS
TArray<ETbEnumEnum0> createTestFTbEnumEnum0Array()
{
	TArray<ETbEnumEnum0> TestValueArray;

	ETbEnumEnum0 val = ETbEnumEnum0::TEE0_Value0;
	TestValueArray.Add(val);
	return TestValueArray;
}


TArray<ETbEnumEnum1> createTestFTbEnumEnum1Array()
{
	TArray<ETbEnumEnum1> TestValueArray;

	ETbEnumEnum1 val = ETbEnumEnum1::TEE1_Value1;
	TestValueArray.Add(val);
	return TestValueArray;
}


TArray<ETbEnumEnum2> createTestFTbEnumEnum2Array()
{
	TArray<ETbEnumEnum2> TestValueArray;

	ETbEnumEnum2 val = ETbEnumEnum2::TEE2_Value2;
	TestValueArray.Add(val);
	return TestValueArray;
}


TArray<ETbEnumEnum3> createTestFTbEnumEnum3Array()
{
	TArray<ETbEnumEnum3> TestValueArray;

	ETbEnumEnum3 val = ETbEnumEnum3::TEE3_Value3;
	TestValueArray.Add(val);
	return TestValueArray;
}



#endif // WITH_DEV_AUTOMATION_TESTS
