// SPDX-FileCopyrightText: Copyright ApiGear UG and Epic Games, Inc.
// SPDX-License-Identifier: MIT
// This file has been generated by the ApiGear Code Generator.
// Do not edit. Changes will be lost when the code is re-generated.

#include "Testbed2Editor.h"
#include "ISettingsModule.h"
#include "PropertyEditorModule.h"
#include "Testbed2Settings.h"
#include "Testbed2ConnectionSettings.h"

#define LOCTEXT_NAMESPACE "Testbed2Editor"

void FTestbed2EditorModule::StartupModule()
{
	// register settings
	ISettingsModule* SettingsModule = FModuleManager::GetModulePtr<ISettingsModule>("Settings");

	if (SettingsModule != nullptr)
	{
		SettingsModule->RegisterSettings("Project", "Plugins", "ApiGear Testbed2", LOCTEXT("Testbed2SettingsName", "ApiGear Testbed2"), LOCTEXT("Testbed2SettingsDescription", "Project settings for ApiGear Testbed2 plugin"), GetMutableDefault<UTestbed2Settings>());
	}

	// register details customization
	FPropertyEditorModule& PropertyModule = FModuleManager::LoadModuleChecked<FPropertyEditorModule>(TEXT("PropertyEditor"));
	PropertyModule.RegisterCustomClassLayout("Testbed2Settings", FOnGetDetailCustomizationInstance::CreateStatic(&FTestbed2ConnectionSettingsDetails::MakeInstance));
}

void FTestbed2EditorModule::ShutdownModule()
{
	// unregister settings
	ISettingsModule* SettingsModule = FModuleManager::GetModulePtr<ISettingsModule>("Settings");

	if (SettingsModule != nullptr)
	{
		SettingsModule->UnregisterSettings("Project", "Plugins", "ApiGear Testbed2");
	}
}

IMPLEMENT_MODULE(FTestbed2EditorModule, Testbed2Editor)

#undef LOCTEXT_NAMESPACE
