// SPDX-FileCopyrightText: Copyright ApiGear UG and Epic Games, Inc.
// SPDX-License-Identifier: MIT
// This file has been generated by the ApiGear Code Generator.
// Do not edit. Changes will be lost when the code is re-generated.
#include "TbSame2/Tests/TbSame2TestsCommon.h"
#include "TbSame2/Generated/api/TbSame2_data.h"
#include "Misc/AutomationTest.h"

#if WITH_DEV_AUTOMATION_TESTS
FTbSame2Struct1 createTestFTbSame2Struct1()
{
	FTbSame2Struct1 TestValue;

	TestValue.field1 = 1;
	TestValue.field2 = 1;
	TestValue.field3 = 1;

	return TestValue;
}

TArray<FTbSame2Struct1> createTestFTbSame2Struct1Array()
{
	TArray<FTbSame2Struct1> TestValueArray;

	TestValueArray.Add(createTestFTbSame2Struct1());

	return TestValueArray;
}

FTbSame2Struct2 createTestFTbSame2Struct2()
{
	FTbSame2Struct2 TestValue;

	TestValue.field1 = 1;
	TestValue.field2 = 1;
	TestValue.field3 = 1;

	return TestValue;
}

TArray<FTbSame2Struct2> createTestFTbSame2Struct2Array()
{
	TArray<FTbSame2Struct2> TestValueArray;

	TestValueArray.Add(createTestFTbSame2Struct2());

	return TestValueArray;
}

TArray<ETbSame2Enum1> createTestFTbSame2Enum1Array()
{
	TArray<ETbSame2Enum1> TestValueArray;

	ETbSame2Enum1 val = ETbSame2Enum1::TS2E1_Value1;
	TestValueArray.Add(val);
	return TestValueArray;
}


TArray<ETbSame2Enum2> createTestFTbSame2Enum2Array()
{
	TArray<ETbSame2Enum2> TestValueArray;

	ETbSame2Enum2 val = ETbSame2Enum2::TS2E2_Value1;
	TestValueArray.Add(val);
	return TestValueArray;
}



#endif // WITH_DEV_AUTOMATION_TESTS
