name: Deploy to Github pages
on:
  push:
    branches:
      - "!*"
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: install dependencies
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: ./docs/package-lock.json
      - run: npm ci
        working-directory: 'docs'
      - run: npm run build
        working-directory: 'docs'

      - name: deploy to github pages
        uses: peaceiris/actions-gh-pages@v4
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build
