// SPDX-FileCopyrightText: Copyright ApiGear UG and Epic Games, Inc.
// SPDX-License-Identifier: MIT
// This file has been generated by the ApiGear Code Generator.
// Do not edit. Changes will be lost when the code is re-generated.

#include "TbSame1Editor.h"
#include "ISettingsModule.h"
#include "PropertyEditorModule.h"
#include "TbSame1Settings.h"
#include "TbSame1ConnectionSettings.h"

#define LOCTEXT_NAMESPACE "TbSame1Editor"

void FTbSame1EditorModule::StartupModule()
{
	// register settings
	ISettingsModule* SettingsModule = FModuleManager::GetModulePtr<ISettingsModule>("Settings");

	if (SettingsModule != nullptr)
	{
		SettingsModule->RegisterSettings("Project", "Plugins", "ApiGear TbSame1", LOCTEXT("TbSame1SettingsName", "ApiGear TbSame1"), LOCTEXT("TbSame1SettingsDescription", "Project settings for ApiGear TbSame1 plugin"), GetMutableDefault<UTbSame1Settings>());
	}

	// register details customization
	FPropertyEditorModule& PropertyModule = FModuleManager::LoadModuleChecked<FPropertyEditorModule>(TEXT("PropertyEditor"));
	PropertyModule.RegisterCustomClassLayout("TbSame1Settings", FOnGetDetailCustomizationInstance::CreateStatic(&FTbSame1ConnectionSettingsDetails::MakeInstance));
}

void FTbSame1EditorModule::ShutdownModule()
{
	// unregister settings
	ISettingsModule* SettingsModule = FModuleManager::GetModulePtr<ISettingsModule>("Settings");

	if (SettingsModule != nullptr)
	{
		SettingsModule->UnregisterSettings("Project", "Plugins", "ApiGear TbSame1");
	}
}

IMPLEMENT_MODULE(FTbSame1EditorModule, TbSame1Editor)

#undef LOCTEXT_NAMESPACE
